#!/usr/bin/env sh

mkdir -p output/www/posts

echo "## Generating index.html"
cargo run

echo "## Sending assets to output/"
rsync -a assets/ output/www/

echo "## Generating 404.html"
multimarkdown parse pages/404.md > output/www/404.html

echo "## Generating about.html"
multimarkdown parse pages/about.md > output/www/about.html

echo "## Generating HTML posts"
for md_file in posts/*.md; do
  base_name=$(basename "$md_file" .md)
  multimarkdown parse "$md_file" > "output/www/posts/${base_name}.html"
done
