#!/usr/bin/env sh

mkdir -p public/posts

echo "## Generating index.html"
cargo run

echo "## Generating 404.html"
multimarkdown parse pages/404.md > public/404.html

echo "## Generating about.html"
multimarkdown parse -r pages/about.md > public/about.html

echo "## Generating HTML posts"
for md_file in posts/*.md; do
  base_name=$(basename "$md_file" .md)
  multimarkdown parse -r "$md_file" > "public/posts/${base_name}.html"
done
